name: rickrogers
favicon: null
layout_spectrum: 0.6720454662572592
typography_spectrum: 0.04303244757466018
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.0119263487868011
  lightness: 0.8774188049137592
  saturation: 0.7216005746740848
  rhythmicContrast: 0.4754594061523676
purpose: []
