name: rickrogers
favicon: null
layout_spectrum: 0
typography_spectrum: 0.0676
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060606'
    - '#a96049'
    - '#006b4f'
    - '#95fefe'
    - '#cfacfa'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
