name: rickrogers
favicon: null
layout_spectrum: 1
typography_spectrum: 0.71046
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d11220'
    - '#15141b'
    - '#fcb247'
    - '#cf702f'
    - '#6e62bf'
  brandStrength: 0.625
  lightness: 0.1875
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
